name: OSV Scanner

on:
  pull_request:
    branches:
      - main
      - development
  merge_group:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development
  schedule:
    - cron: "30 12 * * 1"
  workflow_dispatch:

permissions: read-all

jobs:
  scan:
    name: Dependency vulnerability scan
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.1
        with:
          scan-args: |-
            --recursive
            ./
