name: OSV Scanner

on:
  pull_request:
    branches:
      - main
      - development
  merge_group:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development
  schedule:
    - cron: "30 12 * * 1"
  workflow_dispatch:

permissions: read-all

jobs:
  scan:
    name: Dependency vulnerability scan
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@ffff457756fc02fd3b933aabf3705406f57a2e19 # v2.3.1
        with:
          scan-args: |-
            --recursive
            ./
